name=Buehlmann ZHL-16C
version=1.0.2
author=tongl
maintainer=tongl, tommyliu1996@gmail.com
sentence=Buehlmann ZHL-16C decompression model for DIY dive computer
paragraph=Scuba diving decompression calculations using Buehlmann ZHL-16C algorithm with gradient factor
category=Data Processing
url=https://github.com/tl5915/Buehlmann-ZHL-16C
architectures=*
includes=ZHL16C.h